"""added

Revision ID: 2755e7a49d49
Revises: 
Create Date: 2025-08-18 18:33:55.149608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2755e7a49d49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botConfig',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_clinetId', sa.String(), nullable=True),
    sa.Column('bot_secretKey', sa.String(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopify_stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_url', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_token', sa.String(), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(), nullable=True),
    sa.Column('whatsapp_verify_token', sa.String(), nullable=True),
    sa.Column('whatsapp_business_account_id', sa.String(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_url')
    )
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('shopify_store_url', sa.String(), nullable=False),
    sa.Column('session_state', sa.String(), nullable=True),
    sa.Column('cart_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_sessions')
    op.drop_table('shopify_stores')
    op.drop_table('botConfig')
    # ### end Alembic commands ###
