"""added biling

Revision ID: 53f11f45dfbb
Revises: ff9f520a6b1a
Create Date: 2025-08-25 13:56:32.806902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f11f45dfbb'
down_revision: Union[str, Sequence[str], None] = 'ff9f520a6b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('messages_used', sa.Integer(), nullable=True),
    sa.Column('messages_limit', sa.Integer(), nullable=True),
    sa.Column('messages_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['shopify_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('free_usage_tracking')
    # ### end Alembic commands ###
